run:
  timeout: 10m

linters:
  disable-all:  true
  enable:
    - deadcode
    - gosimple
    - govet
    - ineffassign
    - misspell
    - unused
    - varcheck
    - staticcheck
    - errcheck
    - typecheck
    - goimports
    - dupl
    - nakedret
    - stylecheck
    - gofmt
    - revive
    - structcheck
  
linters-settings:
  gofmt:
    simplify: true
  dupl:
    threshold: 400