version: v2beta1

vars:
  LOFT_IMAGE: loftsh/loft

deployments:
  loft:
    helm:
      chart:
        name: loft
        repo: https://charts.loft.sh

dev:
  loft:
    imageSelector: ${LOFT_IMAGE}
    ports:
      - port: 8443:10443

pipelines:
  e2e:
    run: |-
      # Ensure pull secrets
      ensure_pull_secrets --all
      
      # Deploy loft
      create_deployments --all
      
      # Start port-forwarding
      start_dev loft
      
      # Run the tests
      make testacc
      
      # Stop port-forwarding
      stop_dev loft

commands:
  deploy-loft: devspace deploy
  purge-loft: devspace purge
  dev: devspace dev
  e2e: devspace run-pipeline e2e