//// Code generated by go-swagger; DO NOT EDIT.

package resources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func SpaceInstanceDataSource() *schema.Resource {
	return nil
}

func SpaceInstancesDataSource() *schema.Resource {
	return nil
}
