//// Code generated by go-swagger; DO NOT EDIT.

package resources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	managementv1 "github.com/loft-sh/api/v3/pkg/apis/management/v1"
	"github.com/loft-sh/loftctl/v3/pkg/client"
	"github.com/loft-sh/terraform-provider-loft/pkg/schemas"
	"github.com/loft-sh/terraform-provider-loft/pkg/utils"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	ctrlclient "sigs.k8s.io/controller-runtime/pkg/client"
)

func VirtualClusterTemplateResource() *schema.Resource {
	return &schema.Resource{
		Description:   "VirtualClusterTemplate holds the information",
		Schema:        virtualClusterTemplateAttributes(),
		CreateContext: virtualClusterTemplateCreate,
		ReadContext:   virtualClusterTemplateRead,
		UpdateContext: virtualClusterTemplateUpdate,
		DeleteContext: virtualClusterTemplateDelete,
		Importer: &schema.ResourceImporter{
			StateContext: schema.ImportStatePassthroughContext,
		},
	}
}

func virtualClusterTemplateAttributes() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"id": {
			Type:        schema.TypeString,
			Computed:    true,
			Description: "Unique identifier for this resource. The format is `<name>`.",
		},
		"metadata": utils.MetadataSchema("VirtualClusterTemplate", true, true),
		"spec": {
			Type: schema.TypeList,
			Elem: &schema.Resource{
				Schema: schemas.ManagementV1VirtualClusterTemplateSpecSchema(),
			},
			Required: true,
		},
	}
}

func virtualClusterTemplateRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	loftClient, ok := meta.(client.Client)
	if !ok {
		return diag.Errorf("Could not access loft client")
	}

	managementClient, err := loftClient.Management()
	if err != nil {
		return diag.FromErr(err)
	}
	_, name := utils.ParseID(d.Id())
	if name == "" {
		return diag.Errorf("`name` is required for all resources")
	}

	instance, err := managementClient.Loft().ManagementV1().VirtualClusterTemplates().Get(ctx, name, metav1.GetOptions{})
	if err != nil {
		return diag.FromErr(err)
	}

	metadata, err := utils.ReadMetadata(instance.ObjectMeta)
	if err != nil {
		return diag.FromErr(err)
	}

	if err := d.Set("metadata", []interface{}{metadata}); err != nil {
		return diag.FromErr(err)
	}

	spec, err := schemas.ReadManagementV1VirtualClusterTemplateSpec(&instance.Spec)
	if err != nil {
		return diag.FromErr(err)
	}

	if err := d.Set("spec", []interface{}{spec}); err != nil {
		return diag.FromErr(err)
	}

	return nil
}

func virtualClusterTemplateCreate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	loftClient, ok := meta.(client.Client)
	if !ok {
		return diag.Errorf("Could not access loft client")
	}

	managementClient, err := loftClient.Management()
	if err != nil {
		return diag.FromErr(err)
	}

	metadata := utils.CreateMetadata(d.Get("metadata").([]interface{}))

	spec := schemas.CreateManagementV1VirtualClusterTemplateSpec(d.Get("spec.0").(map[string]interface{}))

	instance, err := managementClient.Loft().ManagementV1().VirtualClusterTemplates().Create(ctx, &managementv1.VirtualClusterTemplate{
		ObjectMeta: metadata,
		Spec:       *spec,
	}, metav1.CreateOptions{})
	if err != nil {
		return diag.FromErr(err)
	}

	d.SetId(utils.ReadId(instance.ObjectMeta))

	return virtualClusterTemplateRead(ctx, d, meta)
}

func virtualClusterTemplateUpdate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	loftClient, ok := meta.(client.Client)
	if !ok {
		return diag.Errorf("Could not access loft client")
	}

	managementClient, err := loftClient.Management()
	if err != nil {
		return diag.FromErr(err)
	}
	_, name := utils.ParseID(d.Id())
	oldInstance, err := managementClient.Loft().ManagementV1().VirtualClusterTemplates().Get(ctx, name, metav1.GetOptions{})
	if err != nil {
		return diag.FromErr(err)
	}

	modifiedInstance := oldInstance.DeepCopy()

	if d.HasChange("spec") {
		if v, ok := d.Get("spec").([]interface{}); ok && len(v) > 0 {
			modifiedInstance.Spec = *schemas.CreateManagementV1VirtualClusterTemplateSpec(v[0].(map[string]interface{}))
		}
	}

	patch := ctrlclient.MergeFrom(oldInstance)
	rawPatch, err := patch.Data(modifiedInstance)
	if err != nil {
		return diag.FromErr(err)
	}
	if _, err := managementClient.Loft().ManagementV1().VirtualClusterTemplates().Patch(ctx, name, patch.Type(), rawPatch, metav1.PatchOptions{}); err != nil {
		return diag.FromErr(err)
	}

	return virtualClusterTemplateRead(ctx, d, meta)
}

func virtualClusterTemplateDelete(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	loftClient, ok := meta.(client.Client)
	if !ok {
		return diag.Errorf("Could not access loft client")
	}

	managementClient, err := loftClient.Management()
	if err != nil {
		return diag.FromErr(err)
	}

	metadata := utils.CreateMetadata(d.Get("metadata").([]interface{}))
	err = managementClient.Loft().ManagementV1().VirtualClusterTemplates().Delete(ctx, metadata.Name, metav1.DeleteOptions{})
	if err != nil {
		return diag.FromErr(err)
	}

	return nil
}
