//// Code generated by go-swagger; DO NOT EDIT.

package schemas

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	agentstoragev1 "github.com/loft-sh/agentapi/v2/pkg/apis/loft/storage/v1"
	"github.com/loft-sh/terraform-provider-loft/pkg/utils"
)

func StorageV1AppReferenceSchema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"name": {
			Type:        schema.TypeString,
			Description: "Name of the target app",
			Optional:    true,
		},
		"namespace": {
			Type:        schema.TypeString,
			Description: "Namespace specifies in which target namespace the app should get deployed in",
			Optional:    true,
		},
		"parameters": {
			Type:        schema.TypeString,
			Description: "Parameters to use for the app",
			Optional:    true,
		},
		"release_name": {
			Type:        schema.TypeString,
			Description: "ReleaseName is the name of the app release",
			Optional:    true,
		},
		"version": {
			Type:        schema.TypeString,
			Description: "Version of the app",
			Optional:    true,
		},
	}
}

func CreateStorageV1AppReference(data map[string]interface{}) *agentstoragev1.AppReference {
	if !utils.HasKeys(data) {
		return nil
	}

	ret := &agentstoragev1.AppReference{}
	if v, ok := data["name"].(string); ok && len(v) > 0 {
		ret.Name = v
	}

	if v, ok := data["namespace"].(string); ok && len(v) > 0 {
		ret.Namespace = v
	}

	if v, ok := data["parameters"].(string); ok && len(v) > 0 {
		ret.Parameters = v
	}

	if v, ok := data["release_name"].(string); ok && len(v) > 0 {
		ret.ReleaseName = v
	}

	if v, ok := data["version"].(string); ok && len(v) > 0 {
		ret.Version = v
	}

	return ret
}

func ReadStorageV1AppReference(obj *agentstoragev1.AppReference) (interface{}, error) {
	if obj == nil {
		return nil, nil
	}

	values := map[string]interface{}{}
	values["name"] = obj.Name

	values["namespace"] = obj.Namespace

	values["parameters"] = obj.Parameters

	values["release_name"] = obj.ReleaseName

	values["version"] = obj.Version

	return values, nil
}
