//// Code generated by go-swagger; DO NOT EDIT.

package schemas

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	storagev1 "github.com/loft-sh/api/v3/pkg/apis/storage/v1"
	"github.com/loft-sh/terraform-provider-loft/pkg/utils"
)

func StorageV1AutomaticImportVirtualClustersSchema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"enabled": {
			Type:        schema.TypeBool,
			Description: "Enabled specifies if automatic virtual cluster import should be enabled for this project.",
			Optional:    true,
			Default:     false,
		},
	}
}

func CreateStorageV1AutomaticImportVirtualClusters(data map[string]interface{}) *storagev1.AutomaticImportVirtualClusters {
	if !utils.HasKeys(data) {
		return nil
	}

	ret := &storagev1.AutomaticImportVirtualClusters{}
	if v, ok := data["enabled"].(bool); ok {
		ret.Enabled = v
	}

	return ret
}

func ReadStorageV1AutomaticImportVirtualClusters(obj *storagev1.AutomaticImportVirtualClusters) (interface{}, error) {
	if obj == nil {
		return nil, nil
	}

	values := map[string]interface{}{}
	values["enabled"] = obj.Enabled

	return values, nil
}
