//// Code generated by go-swagger; DO NOT EDIT.

package schemas

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	agentstoragev1 "github.com/loft-sh/agentapi/v3/pkg/apis/loft/storage/v1"
	"github.com/loft-sh/terraform-provider-loft/pkg/utils"
)

func StorageV1ChartSecretRefSchema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"project_secret_ref": {
			Type:     schema.TypeList,
			MinItems: 1,
			MaxItems: 1,
			Elem: &schema.Resource{
				Schema: StorageV1ProjectSecretRefSchema(),
			},
			Description: "ProjectSecretRef holds the reference to a project secret",
			Optional:    true,
		},
	}
}

func CreateStorageV1ChartSecretRef(data map[string]interface{}) *agentstoragev1.ChartSecretRef {
	if !utils.HasKeys(data) {
		return nil
	}

	ret := &agentstoragev1.ChartSecretRef{}

	if v, ok := data["project_secret_ref"].([]interface{}); ok && len(v) > 0 && v[0] != nil {
		ret.ProjectSecretRef = CreateStorageV1ProjectSecretRef(v[0].(map[string]interface{}))
	}

	return ret
}

func ReadStorageV1ChartSecretRef(obj *agentstoragev1.ChartSecretRef) (interface{}, error) {
	if obj == nil {
		return nil, nil
	}

	values := map[string]interface{}{}
	projectSecretRef, err := ReadStorageV1ProjectSecretRef(obj.ProjectSecretRef)
	if err != nil {
		return nil, err
	}
	values["project_secret_ref"] = projectSecretRef

	return values, nil
}
