//// Code generated by go-swagger; DO NOT EDIT.

package schemas

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	storagev1 "github.com/loft-sh/api/v3/pkg/apis/storage/v1"
	"github.com/loft-sh/terraform-provider-loft/pkg/utils"
)

func StorageV1ClusterRefSchema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"cluster": {
			Type:        schema.TypeString,
			Description: "Cluster is the connected cluster the space will be created in",
			Optional:    true,
		},
		"namespace": {
			Type:        schema.TypeString,
			Description: "Namespace is the namespace inside the connected cluster holding the space",
			Optional:    true,
		},
	}
}

func CreateStorageV1ClusterRef(data map[string]interface{}) *storagev1.ClusterRef {
	if !utils.HasKeys(data) {
		return nil
	}

	ret := &storagev1.ClusterRef{}
	if v, ok := data["cluster"].(string); ok && len(v) > 0 {
		ret.Cluster = v
	}

	if v, ok := data["namespace"].(string); ok && len(v) > 0 {
		ret.Namespace = v
	}

	return ret
}

func ReadStorageV1ClusterRef(obj *storagev1.ClusterRef) (interface{}, error) {
	if obj == nil {
		return nil, nil
	}

	values := map[string]interface{}{}
	values["cluster"] = obj.Cluster

	values["namespace"] = obj.Namespace

	return values, nil
}
