//// Code generated by go-swagger; DO NOT EDIT.

package schemas

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	storagev1 "github.com/loft-sh/api/v3/pkg/apis/storage/v1"
	"github.com/loft-sh/terraform-provider-loft/pkg/utils"
)

func StorageV1ImportVirtualClustersSpecSchema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"role_mapping": {
			Type: schema.TypeMap,
			Elem: &schema.Schema{
				Type: schema.TypeString,
			},
			Description: "RoleMapping indicates an optional role mapping from a rancher project role to a rancher cluster role. Map to an empty role to exclude users and groups with that role from being synced.",
			Optional:    true,
		},
	}
}

func CreateStorageV1ImportVirtualClustersSpec(data map[string]interface{}) *storagev1.ImportVirtualClustersSpec {
	if !utils.HasKeys(data) {
		return nil
	}

	ret := &storagev1.ImportVirtualClustersSpec{}
	ret.RoleMapping = utils.AttributesToMap(data["role_mapping"].(map[string]interface{}))

	return ret
}

func ReadStorageV1ImportVirtualClustersSpec(obj *storagev1.ImportVirtualClustersSpec) (interface{}, error) {
	if obj == nil {
		return nil, nil
	}

	values := map[string]interface{}{}
	values["role_mapping"] = obj.RoleMapping

	return values, nil
}
