//// Code generated by go-swagger; DO NOT EDIT.

package schemas

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	agentstoragev1 "github.com/loft-sh/agentapi/v2/pkg/apis/loft/storage/v1"
	"github.com/loft-sh/terraform-provider-loft/pkg/utils"
)

func StorageV1InstanceAccessSchema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"default_cluster_role": {
			Type:        schema.TypeString,
			Description: "Specifies which cluster role should get applied to users or teams that do not match a rule below.",
			Optional:    true,
		},
		"rules": {
			Type: schema.TypeList,
			Elem: &schema.Resource{
				Schema: StorageV1InstanceAccessRuleSchema(),
			},
			Description: "Rules defines which users and teams should have which access to the virtual cluster. If no rule matches an authenticated incoming user, the user will get cluster admin access.",
			Optional:    true,
		},
	}
}

func CreateStorageV1InstanceAccess(data map[string]interface{}) *agentstoragev1.InstanceAccess {
	if !utils.HasKeys(data) {
		return nil
	}

	ret := &agentstoragev1.InstanceAccess{}

	if v, ok := data["default_cluster_role"].(string); ok && len(v) > 0 {
		ret.DefaultClusterRole = v
	}

	var rulesItems []agentstoragev1.InstanceAccessRule
	for _, v := range data["rules"].([]interface{}) {
		if item := CreateStorageV1InstanceAccessRule(v.(map[string]interface{})); item != nil {
			rulesItems = append(rulesItems, *item)
		}
	}
	ret.Rules = rulesItems

	return ret
}

func ReadStorageV1InstanceAccess(obj *agentstoragev1.InstanceAccess) (interface{}, error) {
	if obj == nil {
		return nil, nil
	}

	values := map[string]interface{}{}
	values["default_cluster_role"] = obj.DefaultClusterRole
	var rulesItems []interface{}
	for _, v := range obj.Rules {
		item, err := ReadStorageV1InstanceAccessRule(&v)
		if err != nil {
			return nil, err
		}
		rulesItems = append(rulesItems, item)
	}
	values["rules"] = rulesItems
	return values, nil
}
