//// Code generated by go-swagger; DO NOT EDIT.

package schemas

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	storagev1 "github.com/loft-sh/api/v3/pkg/apis/storage/v1"
	"github.com/loft-sh/terraform-provider-loft/pkg/utils"
)

func StorageV1NamespacePatternSchema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"space": {
			Type:        schema.TypeString,
			Description: "Space holds the namespace pattern to use for space instances",
			Optional:    true,
		},
		"virtual_cluster": {
			Type:        schema.TypeString,
			Description: "VirtualCluster holds the namespace pattern to use for virtual cluster instances",
			Optional:    true,
		},
	}
}

func CreateStorageV1NamespacePattern(data map[string]interface{}) *storagev1.NamespacePattern {
	if !utils.HasKeys(data) {
		return nil
	}

	ret := &storagev1.NamespacePattern{}
	if v, ok := data["space"].(string); ok && len(v) > 0 {
		ret.Space = v
	}

	if v, ok := data["virtual_cluster"].(string); ok && len(v) > 0 {
		ret.VirtualCluster = v
	}

	return ret
}

func ReadStorageV1NamespacePattern(obj *storagev1.NamespacePattern) (interface{}, error) {
	if obj == nil {
		return nil, nil
	}

	values := map[string]interface{}{}
	values["space"] = obj.Space

	values["virtual_cluster"] = obj.VirtualCluster

	return values, nil
}
