//// Code generated by go-swagger; DO NOT EDIT.

package schemas

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	agentstoragev1 "github.com/loft-sh/agentapi/v3/pkg/apis/loft/storage/v1"
	"github.com/loft-sh/terraform-provider-loft/pkg/utils"
)

func StorageV1ProjectSecretRefSchema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"key": {
			Type:        schema.TypeString,
			Description: "Key of the project secret to use.",
			Optional:    true,
		},
		"name": {
			Type:        schema.TypeString,
			Description: "Name of the project secret to use.",
			Optional:    true,
		},
		"project": {
			Type:        schema.TypeString,
			Description: "Project is the project name where the secret is located in.",
			Optional:    true,
		},
	}
}

func CreateStorageV1ProjectSecretRef(data map[string]interface{}) *agentstoragev1.ProjectSecretRef {
	if !utils.HasKeys(data) {
		return nil
	}

	ret := &agentstoragev1.ProjectSecretRef{}
	if v, ok := data["key"].(string); ok && len(v) > 0 {
		ret.Key = v
	}

	if v, ok := data["name"].(string); ok && len(v) > 0 {
		ret.Name = v
	}

	if v, ok := data["project"].(string); ok && len(v) > 0 {
		ret.Project = v
	}

	return ret
}

func ReadStorageV1ProjectSecretRef(obj *agentstoragev1.ProjectSecretRef) (interface{}, error) {
	if obj == nil {
		return nil, nil
	}

	values := map[string]interface{}{}
	values["key"] = obj.Key

	values["name"] = obj.Name

	values["project"] = obj.Project

	return values, nil
}
