//// Code generated by go-swagger; DO NOT EDIT.

package schemas

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	storagev1 "github.com/loft-sh/api/v2/pkg/apis/storage/v1"
	"github.com/loft-sh/terraform-provider-loft/pkg/utils"
)

func StorageV1QuotasSchema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"project": {
			Type: schema.TypeMap,
			Elem: &schema.Schema{
				Type: schema.TypeString,
			},
			Description: "Project holds the quotas for the whole project",
			Optional:    true,
		},
		"user": {
			Type: schema.TypeMap,
			Elem: &schema.Schema{
				Type: schema.TypeString,
			},
			Description: "User holds the quotas per user / team",
			Optional:    true,
		},
	}
}

func CreateStorageV1Quotas(data map[string]interface{}) *storagev1.Quotas {
	if !utils.HasKeys(data) {
		return nil
	}

	ret := &storagev1.Quotas{}
	ret.Project = utils.AttributesToMap(data["project"].(map[string]interface{}))

	ret.User = utils.AttributesToMap(data["user"].(map[string]interface{}))

	return ret
}

func ReadStorageV1Quotas(obj *storagev1.Quotas) (interface{}, error) {
	if obj == nil {
		return nil, nil
	}

	values := map[string]interface{}{}
	values["project"] = obj.Project

	values["user"] = obj.User

	return values, nil
}
