//// Code generated by go-swagger; DO NOT EDIT.

package schemas

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	storagev1 "github.com/loft-sh/api/v3/pkg/apis/storage/v1"
	"github.com/loft-sh/terraform-provider-loft/pkg/utils"
)

func StorageV1RancherProjectRefSchema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"cluster": {
			Type:        schema.TypeString,
			Description: "Cluster defines the Rancher cluster ID Needs to be the same id within Loft",
			Optional:    true,
		},
		"project": {
			Type:        schema.TypeString,
			Description: "Project defines the Rancher project ID",
			Optional:    true,
		},
	}
}

func CreateStorageV1RancherProjectRef(data map[string]interface{}) *storagev1.RancherProjectRef {
	if !utils.HasKeys(data) {
		return nil
	}

	ret := &storagev1.RancherProjectRef{}
	if v, ok := data["cluster"].(string); ok && len(v) > 0 {
		ret.Cluster = v
	}

	if v, ok := data["project"].(string); ok && len(v) > 0 {
		ret.Project = v
	}

	return ret
}

func ReadStorageV1RancherProjectRef(obj *storagev1.RancherProjectRef) (interface{}, error) {
	if obj == nil {
		return nil, nil
	}

	values := map[string]interface{}{}
	values["cluster"] = obj.Cluster

	values["project"] = obj.Project

	return values, nil
}
