//// Code generated by go-swagger; DO NOT EDIT.

package schemas

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	storagev1 "github.com/loft-sh/api/v3/pkg/apis/storage/v1"
	"github.com/loft-sh/terraform-provider-loft/pkg/utils"
)

func StorageV1RequireTemplateSchema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"disabled": {
			Type:        schema.TypeBool,
			Description: "If true, all users within the project will be allowed to create a new instance without a template. By default, only admins are allowed to create a new instance without a template.",
			Optional:    true,
			Default:     false,
		},
	}
}

func CreateStorageV1RequireTemplate(data map[string]interface{}) *storagev1.RequireTemplate {
	if !utils.HasKeys(data) {
		return nil
	}

	ret := &storagev1.RequireTemplate{}
	if v, ok := data["disabled"].(bool); ok {
		ret.Disabled = v
	}

	return ret
}

func ReadStorageV1RequireTemplate(obj *storagev1.RequireTemplate) (interface{}, error) {
	if obj == nil {
		return nil, nil
	}

	values := map[string]interface{}{}
	values["disabled"] = obj.Disabled

	return values, nil
}
