//// Code generated by go-swagger; DO NOT EDIT.

package schemas

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	storagev1 "github.com/loft-sh/api/v3/pkg/apis/storage/v1"
	"github.com/loft-sh/terraform-provider-loft/pkg/utils"
)

func StorageV1SpaceInstanceTemplateDefinitionSchema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"metadata": {
			Type:     schema.TypeList,
			MinItems: 1,
			MaxItems: 1,
			Elem: &schema.Resource{
				Schema: StorageV1TemplateMetadataSchema(),
			},
			Description: "The space instance metadata",
			Optional:    true,
			Computed:    true,
		},
	}
}

func CreateStorageV1SpaceInstanceTemplateDefinition(data map[string]interface{}) *storagev1.SpaceInstanceTemplateDefinition {
	if !utils.HasKeys(data) {
		return nil
	}

	ret := &storagev1.SpaceInstanceTemplateDefinition{}

	if v, ok := data["metadata"].([]interface{}); ok && len(v) > 0 && v[0] != nil {
		ret.TemplateMetadata = *CreateStorageV1TemplateMetadata(v[0].(map[string]interface{}))
	}

	return ret
}

func ReadStorageV1SpaceInstanceTemplateDefinition(obj *storagev1.SpaceInstanceTemplateDefinition) (interface{}, error) {
	if obj == nil {
		return nil, nil
	}

	values := map[string]interface{}{}

	metadata, err := ReadStorageV1TemplateMetadata(&obj.TemplateMetadata)
	if err != nil {
		return nil, err
	}
	if metadata != nil {
		values["metadata"] = []interface{}{metadata}
	}

	return values, nil
}
