//// Code generated by go-swagger; DO NOT EDIT.

package schemas

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	storagev1 "github.com/loft-sh/api/v2/pkg/apis/storage/v1"
	"github.com/loft-sh/terraform-provider-loft/pkg/utils"
)

func StorageV1TemplateMetadataSchema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"annotations": {
			Type: schema.TypeMap,
			Elem: &schema.Schema{
				Type: schema.TypeString,
			},
			Description: "Annotations are annotations on the object",
			Optional:    true,
		},
		"labels": {
			Type: schema.TypeMap,
			Elem: &schema.Schema{
				Type: schema.TypeString,
			},
			Description: "Labels are labels on the object",
			Optional:    true,
		},
	}
}

func CreateStorageV1TemplateMetadata(data map[string]interface{}) *storagev1.TemplateMetadata {
	if !utils.HasKeys(data) {
		return nil
	}

	ret := &storagev1.TemplateMetadata{}

	ret.Annotations = utils.AttributesToMap(data["annotations"].(map[string]interface{}))

	ret.Labels = utils.AttributesToMap(data["labels"].(map[string]interface{}))

	return ret
}

func ReadStorageV1TemplateMetadata(obj *storagev1.TemplateMetadata) (interface{}, error) {
	if obj == nil {
		return nil, nil
	}

	values := map[string]interface{}{}
	values["annotations"] = obj.Annotations
	values["labels"] = obj.Labels
	return values, nil
}
