//// Code generated by go-swagger; DO NOT EDIT.

package schemas

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func StorageV1UserOrTeamSchema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"team": {
			Type:        schema.TypeString,
			Description: "Team specifies a Loft team.",
			Optional:    true,
		},
		"user": {
			Type:        schema.TypeString,
			Description: "User specifies a Loft user.",
			Optional:    true,
		},
	}
}
