//// Code generated by go-swagger; DO NOT EDIT.

package schemas

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	storagev1 "github.com/loft-sh/api/v2/pkg/apis/storage/v1"
	"github.com/loft-sh/terraform-provider-loft/pkg/utils"
)

func StorageV1UserOrTeamSchema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"team": {
			Type:        schema.TypeString,
			Description: "Team specifies a Loft team.",
			Optional:    true,
		},
		"user": {
			Type:        schema.TypeString,
			Description: "User specifies a Loft user.",
			Optional:    true,
		},
	}
}

func CreateStorageV1UserOrTeam(data map[string]interface{}) *storagev1.UserOrTeam {
	if !utils.HasKeys(data) {
		return nil
	}

	ret := &storagev1.UserOrTeam{}
	if v, ok := data["team"].(string); ok && len(v) > 0 {
		ret.Team = v
	}

	if v, ok := data["user"].(string); ok && len(v) > 0 {
		ret.User = v
	}

	return ret
}

func ReadStorageV1UserOrTeam(obj *storagev1.UserOrTeam) (interface{}, error) {
	if obj == nil {
		return nil, nil
	}

	values := map[string]interface{}{}
	values["team"] = obj.Team

	values["user"] = obj.User

	return values, nil
}
