//// Code generated by go-swagger; DO NOT EDIT.

package schemas

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	agentstoragev1 "github.com/loft-sh/agentapi/v3/pkg/apis/loft/storage/v1"
	"github.com/loft-sh/terraform-provider-loft/pkg/utils"
)

func StorageV1VirtualClusterHelmChartSchema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"name": {
			Type:        schema.TypeString,
			Description: "the name of the helm chart",
			Optional:    true,
		},
		"repo": {
			Type:        schema.TypeString,
			Description: "the repo of the helm chart",
			Optional:    true,
		},
		"version": {
			Type:        schema.TypeString,
			Description: "the version of the helm chart to use",
			Optional:    true,
		},
	}
}

func CreateStorageV1VirtualClusterHelmChart(data map[string]interface{}) *agentstoragev1.VirtualClusterHelmChart {
	if !utils.HasKeys(data) {
		return nil
	}

	ret := &agentstoragev1.VirtualClusterHelmChart{}
	if v, ok := data["name"].(string); ok && len(v) > 0 {
		ret.Name = v
	}

	if v, ok := data["repo"].(string); ok && len(v) > 0 {
		ret.Repo = v
	}

	if v, ok := data["version"].(string); ok && len(v) > 0 {
		ret.Version = v
	}

	return ret
}

func ReadStorageV1VirtualClusterHelmChart(obj *agentstoragev1.VirtualClusterHelmChart) (interface{}, error) {
	if obj == nil {
		return nil, nil
	}

	values := map[string]interface{}{}
	values["name"] = obj.Name

	values["repo"] = obj.Repo

	values["version"] = obj.Version

	return values, nil
}
