//// Code generated by go-swagger; DO NOT EDIT.

package schemas

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	agentstoragev1 "github.com/loft-sh/agentapi/v3/pkg/apis/loft/storage/v1"
	"github.com/loft-sh/terraform-provider-loft/pkg/utils"
)

func StorageV1VirtualClusterAccessPointSchema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"ingress": {
			Type:     schema.TypeList,
			MinItems: 1,
			MaxItems: 1,
			Elem: &schema.Resource{
				Schema: StorageV1VirtualClusterAccessPointIngressSpecSchema(),
			},
			Description: "Ingress defines virtual cluster access via ingress",
			Optional:    true,
		},
	}
}

func CreateStorageV1VirtualClusterAccessPoint(data map[string]interface{}) *agentstoragev1.VirtualClusterAccessPoint {
	if !utils.HasKeys(data) {
		return nil
	}

	ret := &agentstoragev1.VirtualClusterAccessPoint{}

	if v, ok := data["ingress"].([]interface{}); ok && len(v) > 0 && v[0] != nil {
		ret.Ingress = *CreateStorageV1VirtualClusterAccessPointIngressSpec(v[0].(map[string]interface{}))
	}

	return ret
}

func ReadStorageV1VirtualClusterAccessPoint(obj *agentstoragev1.VirtualClusterAccessPoint) (interface{}, error) {
	if obj == nil {
		return nil, nil
	}

	values := map[string]interface{}{}
	ingress, err := ReadStorageV1VirtualClusterAccessPointIngressSpec(&obj.Ingress)
	if err != nil {
		return nil, err
	}
	if ingress != nil {
		values["ingress"] = []interface{}{ingress}
	}

	return values, nil
}
