//// Code generated by go-swagger; DO NOT EDIT.

package schemas

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func StorageV1VirtualClusterHelmChartSchema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"name": {
			Type:        schema.TypeString,
			Description: "the name of the helm chart",
			Optional:    true,
		},
		"repo": {
			Type:        schema.TypeString,
			Description: "the repo of the helm chart",
			Optional:    true,
		},
		"version": {
			Type:        schema.TypeString,
			Description: "the version of the helm chart to use",
			Optional:    true,
		},
	}
}
