//// Code generated by go-swagger; DO NOT EDIT.

package schemas

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	storagev1 "github.com/loft-sh/api/v3/pkg/apis/storage/v1"
	"github.com/loft-sh/terraform-provider-loft/pkg/utils"
)

func StorageV1VirtualClusterTemplateSpaceTemplateRefSchema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"name": {
			Type:        schema.TypeString,
			Description: "Name of the space template",
			Optional:    true,
		},
	}
}

func CreateStorageV1VirtualClusterTemplateSpaceTemplateRef(data map[string]interface{}) *storagev1.VirtualClusterTemplateSpaceTemplateRef {
	if !utils.HasKeys(data) {
		return nil
	}

	ret := &storagev1.VirtualClusterTemplateSpaceTemplateRef{}
	if v, ok := data["name"].(string); ok && len(v) > 0 {
		ret.Name = v
	}

	return ret
}

func ReadStorageV1VirtualClusterTemplateSpaceTemplateRef(obj *storagev1.VirtualClusterTemplateSpaceTemplateRef) (interface{}, error) {
	if obj == nil {
		return nil, nil
	}

	values := map[string]interface{}{}
	values["name"] = obj.Name

	return values, nil
}
