//// Code generated by go-swagger; DO NOT EDIT.

package schemas

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	agentstoragev1 "github.com/loft-sh/agentapi/v2/pkg/apis/loft/storage/v1"
	"github.com/loft-sh/terraform-provider-loft/pkg/utils"
)

func StorageV1VirtualClusterAccessPointSchema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"ingress": {
			Type:     schema.TypeList,
			MinItems: 1,
			MaxItems: 1,
			Elem: &schema.Resource{
				Schema: StorageV1VirtualClusterAccessPointIngressSpecSchema(),
			},
			Description: "Ingress defines virtual cluster access via ingress",
			Optional:    true,
		},
	}
}

func CreateStorageV1VirtualClusterAccessPoint(in []interface{}) *agentstoragev1.VirtualClusterAccessPoint {
	if !utils.HasValue(in) {
		return nil
	}

	ret := &agentstoragev1.VirtualClusterAccessPoint{}

	data := in[0].(map[string]interface{})

	if value := CreateStorageV1VirtualClusterAccessPointIngressSpec(data["ingress"].([]interface{})); value != nil {
		ret.Ingress = *value
	}

	return ret
}

func ReadStorageV1VirtualClusterAccessPoint(obj *agentstoragev1.VirtualClusterAccessPoint) (interface{}, error) {
	values := map[string]interface{}{}

	ingress, err := ReadStorageV1VirtualClusterAccessPointIngressSpec(&obj.Ingress)
	if err != nil {
		return nil, err
	}
	values["ingress"] = ingress

	return values, nil
}
