//// Code generated by go-swagger; DO NOT EDIT.

package schemas

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func StorageV1VirtualClusterHelmReleaseSchema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"chart": {
			Type:     schema.TypeList,
			MinItems: 1,
			MaxItems: 1,
			Elem: &schema.Resource{
				Schema: StorageV1VirtualClusterHelmChartSchema(),
			},
			Description: "infos about what chart to deploy",
			Optional:    true,
		},
		"values": {
			Type:        schema.TypeString,
			Description: "the values for the given chart",
			Optional:    true,
		},
	}
}
