//// Code generated by go-swagger; DO NOT EDIT.

package resources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/loft-sh/terraform-provider-loft/loft/schemas"
	"github.com/loft-sh/terraform-provider-loft/loft/utils"
)

func ProjectResource() *schema.Resource {
	return &schema.Resource{
		Description:   "",
		Schema:        projectAttributes(),
		CreateContext: projectCreate,
		ReadContext:   projectRead,
		UpdateContext: projectUpdate,
		DeleteContext: projectDelete,
		Importer: &schema.ResourceImporter{
			StateContext: schema.ImportStatePassthroughContext,
		},
	}
}

func projectAttributes() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"metadata": utils.MetadataSchema("Project", true),
		"spec": {
			Type:     schema.TypeList,
			Optional: true,
			Elem: &schema.Resource{
				Schema: schemas.ManagementV1ProjectSpecSchema(),
			},
		},
	}
}

func projectCreate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	return nil
}

func projectRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	return nil
}

func projectUpdate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	return nil
}

func projectDelete(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	return nil
}
