//// Code generated by go-swagger; DO NOT EDIT.

package resources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/loft-sh/terraform-provider-loft/loft/schemas"
	"github.com/loft-sh/terraform-provider-loft/loft/utils"
)

func SpaceInstanceResource() *schema.Resource {
	return &schema.Resource{
		Description:   "",
		Schema:        spaceInstanceAttributes(),
		CreateContext: spaceInstanceCreate,
		ReadContext:   spaceInstanceRead,
		UpdateContext: spaceInstanceUpdate,
		DeleteContext: spaceInstanceDelete,
		Importer: &schema.ResourceImporter{
			StateContext: schema.ImportStatePassthroughContext,
		},
	}
}

func spaceInstanceAttributes() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"metadata": utils.MetadataSchema("SpaceInstance", true),
		"spec": {
			Type:     schema.TypeList,
			Optional: true,
			Elem: &schema.Resource{
				Schema: schemas.ManagementV1SpaceInstanceSpecSchema(),
			},
		},
	}
}

func spaceInstanceCreate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	return nil
}

func spaceInstanceRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	return nil
}

func spaceInstanceUpdate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	return nil
}

func spaceInstanceDelete(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	return nil
}
