//// Code generated by go-swagger; DO NOT EDIT.

package resources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/loft-sh/terraform-provider-loft/loft/schemas"
	"github.com/loft-sh/terraform-provider-loft/loft/utils"
)

func VirtualClusterInstanceResource() *schema.Resource {
	return &schema.Resource{
		Description:   "",
		Schema:        virtualClusterInstanceAttributes(),
		CreateContext: virtualClusterInstanceCreate,
		ReadContext:   virtualClusterInstanceRead,
		UpdateContext: virtualClusterInstanceUpdate,
		DeleteContext: virtualClusterInstanceDelete,
		Importer: &schema.ResourceImporter{
			StateContext: schema.ImportStatePassthroughContext,
		},
	}
}

func virtualClusterInstanceAttributes() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"metadata": utils.MetadataSchema("VirtualClusterInstance", true),
		"spec": {
			Type:     schema.TypeList,
			Optional: true,
			Elem: &schema.Resource{
				Schema: schemas.ManagementV1VirtualClusterInstanceSpecSchema(),
			},
			ConfigMode: schema.SchemaConfigModeAttr,
		},
	}
}

func virtualClusterInstanceCreate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	return nil
}

func virtualClusterInstanceRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	return nil
}

func virtualClusterInstanceUpdate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	return nil
}

func virtualClusterInstanceDelete(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	return nil
}
