//// Code generated by go-swagger; DO NOT EDIT.

package schemas

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func StorageV1AllowedTemplateSchema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"group": {
			Type:        schema.TypeString,
			Description: "Group of the template that is allowed. Currently only supports storage.loft.sh",
			Optional:    true,
		},
		"is_default": {
			Type:        schema.TypeBool,
			Description: "IsDefault specifies if the template should be used as a default",
			Optional:    true,
		},
		"kind": {
			Type:        schema.TypeString,
			Description: "Kind of the template that is allowed. Currently only supports VirtualClusterTemplate & SpaceTemplate",
			Optional:    true,
		},
		"name": {
			Type:        schema.TypeString,
			Description: "Name of the template",
			Optional:    true,
		},
	}
}
