//// Code generated by go-swagger; DO NOT EDIT.

package schemas

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func StorageV1AppReferenceSchema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"name": {
			Type:        schema.TypeString,
			Description: "Name of the target app",
			Optional:    true,
		},
		"namespace": {
			Type:        schema.TypeString,
			Description: "Namespace specifies in which target namespace the app should get deployed in",
			Optional:    true,
		},
		"parameters": {
			Type:        schema.TypeString,
			Description: "Parameters to use for the app",
			Optional:    true,
		},
		"release_name": {
			Type:        schema.TypeString,
			Description: "ReleaseName is the name of the app release",
			Optional:    true,
		},
		"version": {
			Type:        schema.TypeString,
			Description: "Version of the app",
			Optional:    true,
		},
	}
}
