//// Code generated by go-swagger; DO NOT EDIT.

package schemas

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func StorageV1ArgoProjectRoleSchema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"description": {
			Type:        schema.TypeString,
			Description: "Description to add to the ArgoCD project.",
			Optional:    true,
		},
		"groups": {
			Type: schema.TypeList,
			Elem: &schema.Schema{
				Type: schema.TypeString,
			},
			Description: "Groups is a list of OIDC group names to bind to the role.",
			Optional:    true,
		},
		"name": {
			Type:        schema.TypeString,
			Description: "Name of the ArgoCD role to attach to the project.",
			Optional:    true,
		},
		"rules": {
			Type: schema.TypeList,
			Elem: &schema.Resource{
				Schema: StorageV1ArgoProjectPolicyRuleSchema(),
			},
			Description: "Rules ist a list of policy rules to attach to the role.",
			Optional:    true,
		},
	}
}
