//// Code generated by go-swagger; DO NOT EDIT.

package schemas

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func StorageV1ArgoProjectPolicyRuleSchema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"action": {
			Type:        schema.TypeString,
			Description: "Action is one of \"*\", \"get\", \"create\", \"update\", \"delete\", \"sync\", or \"override\".",
			Optional:    true,
		},
		"application": {
			Type:        schema.TypeString,
			Description: "Application is the ArgoCD project/repository to apply the rule to.",
			Optional:    true,
		},
		"permission": {
			Type:        schema.TypeBool,
			Description: "Allow applies the \"allow\" permission to the rule, if allow is not set, the permission will always be set to \"deny\".",
			Optional:    true,
		},
	}
}
