//// Code generated by go-swagger; DO NOT EDIT.

package schemas

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func StorageV1ArgoProjectSpecMetadataSchema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"description": {
			Type:        schema.TypeString,
			Description: "Description to add to the ArgoCD project.",
			Optional:    true,
		},
		"extra_annotations": {
			Type: schema.TypeMap,
			Elem: &schema.Schema{
				Type: schema.TypeString,
			},
			Description: "ExtraAnnotations are optional annotations that can be attached to the project in ArgoCD.",
			Optional:    true,
		},
		"extra_labels": {
			Type: schema.TypeMap,
			Elem: &schema.Schema{
				Type: schema.TypeString,
			},
			Description: "ExtraLabels are optional labels that can be attached to the project in ArgoCD.",
			Optional:    true,
		},
	}
}
