//// Code generated by go-swagger; DO NOT EDIT.

package schemas

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func StorageV1InstanceAccessSchema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"default_cluster_role": {
			Type:        schema.TypeString,
			Description: "Specifies which cluster role should get applied to users or teams that do not match a rule below.",
			Optional:    true,
		},
		"rules": {
			Type: schema.TypeList,
			Elem: &schema.Resource{
				Schema: StorageV1InstanceAccessRuleSchema(),
			},
			Description: "Rules defines which users and teams should have which access to the virtual cluster. If no rule matches an authenticated incoming user, the user will get cluster admin access.",
			Optional:    true,
		},
	}
}
