//// Code generated by go-swagger; DO NOT EDIT.

package schemas

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func StorageV1MemberSchema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"cluster_role": {
			Type:        schema.TypeString,
			Description: "ClusterRole is the assigned role for the above member",
			Optional:    true,
		},
		"group": {
			Type:        schema.TypeString,
			Description: "Group of the member. Currently only supports storage.loft.sh",
			Optional:    true,
		},
		"kind": {
			Type:        schema.TypeString,
			Description: "Kind is the kind of the member. Currently either User or Team",
			Optional:    true,
		},
		"name": {
			Type:        schema.TypeString,
			Description: "Name of the member",
			Optional:    true,
		},
	}
}
