//// Code generated by go-swagger; DO NOT EDIT.

package schemas

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func StorageV1QuotasSchema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"project": {
			Type: schema.TypeMap,
			Elem: &schema.Schema{
				Type: schema.TypeString,
			},
			Description: "Project holds the quotas for the whole project",
			Optional:    true,
		},
		"user": {
			Type: schema.TypeMap,
			Elem: &schema.Schema{
				Type: schema.TypeString,
			},
			Description: "User holds the quotas per user / team",
			Optional:    true,
		},
	}
}
