//// Code generated by go-swagger; DO NOT EDIT.

package schemas

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func StorageV1TemplateMetadataSchema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"annotations": {
			Type: schema.TypeMap,
			Elem: &schema.Schema{
				Type: schema.TypeString,
			},
			Description: "Annotations are annotations on the object",
			Optional:    true,
		},
		"labels": {
			Type: schema.TypeMap,
			Elem: &schema.Schema{
				Type: schema.TypeString,
			},
			Description: "Labels are labels on the object",
			Optional:    true,
		},
	}
}
