//// Code generated by go-swagger; DO NOT EDIT.

package schemas

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func StorageV1TemplateHelmChartSchema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"insecure_skip_tls_verify": {
			Type:        schema.TypeBool,
			Description: "If tls certificate checks for the chart download should be skipped",
			Optional:    true,
		},
		"name": {
			Type:        schema.TypeString,
			Description: "Name is the chart name in the repository",
			Optional:    true,
		},
		"password": {
			Type:        schema.TypeString,
			Description: "The password that is required for this repository",
			Optional:    true,
		},
		"release_name": {
			Type:        schema.TypeString,
			Description: "ReleaseName is the preferred release name of the app",
			Optional:    true,
		},
		"release_namespace": {
			Type:        schema.TypeString,
			Description: "ReleaseNamespace is the preferred release namespace of the app",
			Optional:    true,
		},
		"repo_url": {
			Type:        schema.TypeString,
			Description: "RepoURL is the repo url where the chart can be found",
			Optional:    true,
		},
		"timeout": {
			Type:        schema.TypeString,
			Description: "Timeout is the time to wait for any individual Kubernetes operation (like Jobs for hooks) (default 5m0s)",
			Optional:    true,
		},
		"username": {
			Type:        schema.TypeString,
			Description: "The username that is required for this repository",
			Optional:    true,
		},
		"values": {
			Type:        schema.TypeString,
			Description: "Values are the values that should get passed to the chart",
			Optional:    true,
		},
		"version": {
			Type:        schema.TypeString,
			Description: "Version is the chart version in the repository",
			Optional:    true,
		},
		"wait": {
			Type:        schema.TypeBool,
			Description: "Wait determines if Loft should wait during deploy for the app to become ready",
			Optional:    true,
		},
	}
}
