//// Code generated by go-swagger; DO NOT EDIT.

package schemas

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func StorageV1VirtualClusterClusterRefSchema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"cluster": {
			Type:        schema.TypeString,
			Description: "Cluster is the connected cluster the space will be created in",
			Optional:    true,
		},
		"namespace": {
			Type:        schema.TypeString,
			Description: "Namespace is the namespace inside the connected cluster holding the space",
			Optional:    true,
		},
		"virtual_cluster": {
			Type:        schema.TypeString,
			Description: "VirtualCluster is the name of the virtual cluster inside the namespace",
			Optional:    true,
		},
	}
}
